AllCops:
    TargetRubyVersion: 2.4
    Exclude:
      - 'db/migrate/**/*'
      - 'db/schema.rb'
      - 'bin/**/*'

Rails:
    Enabled: true

Bundler/OrderedGems:
    Enabled: false

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Style/TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/FormatStringToken:
    Enabled: false

Metrics/LineLength:
    Exclude:
      - 'spec/**/*'
      # Also list here third party config eg:
      # - 'config/initializers/rollbar.rb'

Metrics/BlockLength:
    Exclude:
      - 'spec/**/*'
      - 'config/routes.rb'
